[project]
name = 'Decentralized-Disaster-Resistant-Seed-Banking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.distribution-protocol]
path = 'contracts/distribution-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.seed-registration]
path = 'contracts/seed-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage-monitoring]
path = 'contracts/storage-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.viability-testing]
path = 'contracts/viability-testing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
